version: "3.8"

services:
  backend:
    image: chatapp-backend
    container_name: chatapp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - application

  db:
    image: postgres:alpine
    container_name: chatapp-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  application:

volumes:
  postgres-db:

# services:
#   app:
#     tty: true
#     restart: always
#     image: chatapp
#     container_name: chatapp
#     build: .
#     ports:
#       - 3000:3000
#     env_file:
#       - .env
#     networks:
#       - application
#     depends_on:
#       db:
#         condition: service_healthy
#     volumes:
#       - .:/src/app
#     command: air -c .air.toml

#   db:
#     image: postgres:alpine
#     container_name: chatapp-db
#     environment:
#       - POSTGRES_HOST=${DB_HOST}
#       - POSTGRES_DB=${DB_NAME}
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#     ports:
#       - 5432:5432
#     volumes: 
#       - postgres-db:/var/lib/postgresql/data
#     networks:
#       - application
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   adminer:
#     image: adminer:latest
#     container_name: adminer
#     restart: always
#     ports:
#       - "8080:8080"
#     networks:
#       - application
#     depends_on:
#       db:
#         condition: service_healthy
#     environment:
#       ADMINER_DESIGN: dracula
#       ADMINER_DEFAULT_SERVER: chatapp-db

# networks:
#   application:

# volumes:
#   postgres-db:
